name: Notify Discord with Updated or Added Entries

on:
  push:
    paths:
      - "games.json"
  workflow_dispatch:

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            .venv
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests Pillow colorthief

      - name: Fetch last committed version of games.json
        id: fetch-last-commit
        run: |
          git fetch --depth=2
          git show HEAD^:games.json > previous_games.json || true

      - name: Print Length of Changed Game Names
        run: |
          python notify_discord.py -c

      - name: Manual Approval to Send Changed JSON Data
        id: manual_approval_changes
        uses: peter-evans/manual-approval@v2
        with:
          review: "Do you want to send the changed JSON data? (yes/no)"

      - name: Send Changed JSON Data
        if: ${{ steps.manual_approval_changes.outputs.review == 'yes' }}
        run: |
          python notify_discord.py -y

      - name: Manual Approval to Send Only New Entries
        if: ${{ steps.manual_approval_changes.outputs.review != 'yes' }}
        id: manual_approval_new_entries
        uses: peter-evans/manual-approval@v2
        with:
          review: "Do you want to send only new entries? (yes/no)"

      - name: Send Only New Entries
        if: ${{ steps.manual_approval_new_entries.outputs.review == 'yes' }}
        run: |
          python notify_discord.py -b
