name: Notify Discord with Updated or Added Entries

on:
  push:
    paths:
      - "games.json"
  workflow_dispatch:
    inputs:
      action:
        description: 'Select the action to perform'
        required: true
        type: choice
        options:
          - print_length
          - send_changes
          - send_new_entries

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            .venv
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests Pillow colorthief

      - name: Fetch last committed version of games.json
        id: fetch-last-commit
        run: |
          git fetch --depth=2
          git show HEAD^:games.json > previous_games.json || true

      - name: Print Length of Changed Game Names
        if: ${{ github.event.inputs.action == 'print_length' }}
        run: |
          python notify_discord.py -c

      - name: Confirm to Send Changed JSON Data
        if: ${{ github.event.inputs.action == 'print_length' }}
        id: confirm_send_changes
        run: |
          echo "Do you want to send the changed JSON data? (yes/no)"
          read -r response
          echo "SEND_CHANGES=$response" >> $GITHUB_ENV

      - name: Send Changed JSON Data
        if: ${{ env.SEND_CHANGES == 'yes' }}
        run: |
          python notify_discord.py -y

      - name: Confirm to Send Only New Entries
        if: ${{ github.event.inputs.action == 'print_length' && env.SEND_CHANGES != 'yes' }}
        id: confirm_send_new_entries
        run: |
          echo "Do you want to send only new entries? (yes/no)"
          read -r response
          echo "SEND_NEW_ENTRIES=$response" >> $GITHUB_ENV

      - name: Send Only New Entries
        if: ${{ env.SEND_NEW_ENTRIES == 'yes' }}
        run: |
          python notify_discord.py -b
